### ISSUE TITLE
集成 'vite-plugin-vitepress-demo' 插件后，执行 docs:build 构建完成后进程不退出，导致后续的流水线进行不下去

### ISSUE THREAD

**Issue by dizuncainiao** [aibayanyu20/vite-plugins#1]
![image](https://github.com/aibayanyu20/vite-plugins/assets/40376068/615d01ba-7bcb-4357-9754-6415ab56c492)

拉你的项目构建也是一样，没有退出，所以初步判断插件可能有问题
![image](https://github.com/aibayanyu20/vite-plugins/assets/40376068/f410d9f3-9f4e-4130-a166-de4f9f15a836)

其他不用 'vite-plugin-vitepress-demo' 的项目可以正常退出：
![image](https://github.com/aibayanyu20/vite-plugins/assets/40376068/2630a3e4-fb5b-4f97-b672-9831a5669361)

**Comment by aibayanyu20** [comment]
get我排查一下

**Comment by dizuncainiao** [comment]
> get我排查一下

好的，多谢了

**Comment by aibayanyu20** [comment]
update v2.1.0
