### ISSUE TITLE
该插件和vite-plugin-vue-devtools共同使用时会报错，只对动态样式进行了替换，行内静态代码未替换

### ISSUE THREAD

**Issue by SiegeLionLang** [aibayanyu20/vite-plugins#3]
<img width="530" alt="image" src="https://github.com/user-attachments/assets/20ff033a-0dcd-4dcc-862a-0c6488fcdce5"/>

**Comment by aibayanyu20** [comment]
提供一个完整的复现例子吧

**Comment by aibayanyu20** [comment]
升级到0.0.9
