### ISSUE TITLE
px2viewport插件传参似乎不生效，且似乎无法支持在自定义组件标签中px转vw

### ISSUE THREAD

**Issue by dyb-dev** [aibayanyu20/vite-plugins#5]
安装的版本号:
![image](https://github.com/user-attachments/assets/3b7416d1-154d-49f8-93f9-45943b1707e7)
问题1:
![image](https://github.com/user-attachments/assets/6bef1f45-5f8b-41b8-9d65-4400ef97e482)
问题2:
![image](https://github.com/user-attachments/assets/7db563fa-edfc-4733-86aa-1d23084a5f4f)
<img width="154" alt="image" src="https://github.com/user-attachments/assets/606e2abb-8f4a-4a01-b3f2-14bcbd304f0e">

**Comment by aibayanyu20** [comment]
更新到0.0.11
问题1：默认情况下行内样式是不支持cssOptions的，只有postcss插件支持，可以看下readme，我把目前支持的属性都列出来了其他的暂时还是只有postcss插件支持
目前支持的属性：viewportWidth（行内仅支持数字） 、unitToConvert 、unitPrecision、viewportUnit 、minPixelValue 。

问题2： 已修复

**Comment by dyb-dev** [comment]
> 更新到0.0.11 问题1：默认情况Outline内部样式是不支持cssOptions的，只有postcss插件支持，可以看下readme，我把目前支持的属性都上市来了其他的暂时还是只有postcss插件支持 目前支持的属性：viewportWidth（行内仅支持数字） 、unitToConvert 、unitPrecision、viewportUnit 、minPixelValue 。
> 
> 问题2： 已修复

好滴，目测现在是ok的，谢谢啦!
